"use client";

import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import { Check, Download, FileText, Loader2, QrCode, Search, X, WalletCards, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Tx=Record<string,any>;

export default function AdminFinance(){
 const [rows,setRows]=useState<Tx[]>([]); const [selected,setSelected]=useState<Tx|null>(null); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [status,setStatus]=useState("ALL");
 const load=async()=>{setLoading(true);const {data}=await supabase().from("transactions").select("*").order("created_at",{ascending:false}).limit(1000);setRows(data||[]);setLoading(false)};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(status==="ALL"||r.status===status)&&(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))),[rows,status,query]);
 const update=async(id:string,next:"COMPLETED"|"FAILED")=>{const {data:{session}}=await supabase().auth.getSession();if(!session)return;await fetch("/api/admin/transactions/"+id+"/resolve",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({status:next,reason:next==="FAILED"?"Marked failed by finance administrator":"Marked completed by finance administrator"})});await load();};
 const exportRows=(format:"csv"|"json")=>{const text=format==="json"?JSON.stringify(filtered,null,2):toCsv(filtered);const blob=new Blob([text],{type:format==="json"?"application/json":"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`creatorhub-financial-operations-${Date.now()}.${format}`;a.click();URL.revokeObjectURL(a.href)};
 return <AppShell admin><div className="mx-auto max-w-7xl">
  <p className="text-xs font-bold uppercase tracking-[.16em] text-orange-600">Finance operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Financial operations</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Every initialized transaction remains visible, including pending, completed and failed records. Open any record for the complete gateway and local transaction history.</p>
  <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="All records" value={rows.length}/><Stat label="Pending" value={rows.filter(r=>r.status==="PENDING").length}/><Stat label="Completed" value={rows.filter(r=>r.status==="COMPLETED").length}/><Stat label="Failed" value={rows.filter(r=>r.status==="FAILED").length}/></div>
  <div className="card mt-6 overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 md:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3"><Search size={15} className="text-slate-400"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Reference, user, type, description..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="input w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option>PENDING</option><option>COMPLETED</option><option>FAILED</option></select><button className="btn btn-secondary" onClick={()=>exportRows("csv")}><Download size={15}/> Export CSV</button><button className="btn btn-secondary" onClick={()=>exportRows("json")}><FileText size={15}/> JSON</button></div>
  {loading?<div className="p-12 text-center"><Loader2 className="mx-auto animate-spin text-orange-600"/></div>:<div className="divide-y divide-slate-100">{filtered.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="w-full p-5 text-left hover:bg-slate-50"><div className="grid gap-3 md:grid-cols-[1.6fr_1fr_1fr_1fr] md:items-center"><div><div className="font-mono text-xs font-semibold">{r.reference||r.id}</div><div className="mt-1 text-sm text-slate-600">{r.description||r.type}</div></div><div className="text-sm">{r.type}</div><div className="font-semibold">GH₵{Number(r.amount||0).toFixed(2)} <span className="text-xs font-normal text-slate-400">{r.currency}</span></div><div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{r.status}</span><div className="mt-1 text-[11px] text-slate-400">{new Date(r.created_at).toLocaleString()}</div></div></div></button>)}</div>}
  {!loading&&!filtered.length&&<div className="p-12 text-center text-sm text-slate-500"><WalletCards className="mx-auto mb-2"/>No financial records match this view.</div>}</div>
  {selected&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-4 md:p-8" onClick={()=>setSelected(null)}><div className="mx-auto flex h-full max-w-5xl items-center" onClick={e=>e.stopPropagation()}><div className="max-h-[92vh] w-full overflow-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-600">Financial record</p><h2 className="mt-1 font-mono text-sm">{selected.reference||selected.id}</h2></div><button className="btn btn-secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="grid gap-6 p-6 lg:grid-cols-[1fr_260px]"><div><div className="grid gap-3 sm:grid-cols-3"><Info label="Status" value={selected.status}/><Info label="Amount" value={`GH₵${Number(selected.amount||0).toFixed(2)}`}/><Info label="Type" value={selected.type}/></div><div className="mt-5 rounded-2xl bg-slate-950 p-5 text-white"><div className="text-xs uppercase tracking-wider text-slate-400">Complete transaction payload</div><pre className="mt-3 whitespace-pre-wrap break-words text-xs leading-6">{JSON.stringify(selected,null,2)}</pre></div>{selected.status==="PENDING"&&<div className="mt-4 flex gap-2"><button className="btn btn-primary" onClick={()=>update(selected.id,"COMPLETED")}><Check size={15}/> Mark completed</button><button className="btn btn-secondary" onClick={()=>update(selected.id,"FAILED")}><X size={15}/> Mark failed</button></div>}</div><div><div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><QrCode size={17}/> Record QR</div><img className="mx-auto mt-4 h-48 w-48 rounded-xl border border-slate-200 p-2" src={qrUrl(selected.id)}/><p className="mt-3 text-center text-[11px] text-slate-500">Scan to open this protected financial record.</p></div><div className="mt-4 rounded-2xl border border-slate-200 p-4 text-xs text-slate-500"><ShieldCheck size={16} className="mb-2 text-emerald-600"/>Financial records remain behind administrator authentication.</div></div></div></div></div></div>}
 </div></AppShell>
}
function qrUrl(id:string){return "https://quickchart.io/qr?size=500&text="+encodeURIComponent(window.location.origin+"/admin/finance/"+encodeURIComponent(id))}
function Stat({label,value}:{label:string;value:number}){return <div className="card p-5"><div className="text-2xl font-bold">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div>}
function toCsv(rows:Tx[]){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const esc=(v:any)=>`"${String(typeof v==="object"&&v!==null?JSON.stringify(v):v??"").replaceAll('"','""')}"`;return [keys.join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join("\n"))].join("\n")}
