"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase";
import {Check,Loader2,RefreshCw,Sparkles,AtSign} from "lucide-react";

export default function UsernameSetup(){
 const router=useRouter(); const [name,setName]=useState(""); const [username,setUsername]=useState(""); const [suggestions,setSuggestions]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const suggest=async(n:string)=>{if(!n.trim())return; const r=await fetch("/api/profile/username-suggestions?name="+encodeURIComponent(n)); const d=await r.json();setSuggestions(d.suggestions||[]);};
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase().auth.getUser();if(!user){router.replace("/auth/sign-in");return}const {data:p}=await supabase().from("profiles").select("display_name,username").eq("id",user.id).single();if(p?.username){router.replace("/dashboard");return}setName(p?.display_name||user.email?.split("@")[0]||"Creator");suggest(p?.display_name||user.email?.split("@")[0]||"Creator");setLoading(false)})()},[router]);
 const save=async()=>{const value=username.trim().toLowerCase().replace(/[^a-z0-9._-]/g,"");if(value.length<3)return setError("Username must be at least 3 characters.");setSaving(true);setError("");const {data:{user}}=await supabase().auth.getUser();if(!user){router.replace("/auth/sign-in");return}const {error:e}=await supabase().from("profiles").update({username:value,updated_at:new Date().toISOString()}).eq("id",user.id);if(e)setError(e.code==="23505"?"That username was just taken. Choose another suggestion.":e.message);else router.replace("/dashboard");setSaving(false)};
 if(loading)return <main className="grid min-h-screen place-items-center bg-slate-950"><Loader2 className="animate-spin text-white"/></main>;
 return <main className="min-h-screen bg-[#f5f7fa] px-5 py-10"><div className="mx-auto max-w-xl"><div className="mb-8 flex items-center gap-3"><img src="/creatorhub-mark.svg" className="h-11 w-11" alt="CreatorHub"/><span className="text-xl font-bold">CreatorHub</span></div><div className="rounded-[30px] border border-slate-200 bg-white p-7 shadow-xl sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-slate-950 text-white"><AtSign size={22}/></div><h1 className="mt-6 text-3xl font-bold tracking-tight">Choose your username</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your username is your unique CreatorHub identity. You can use letters, numbers, dots, underscores and hyphens.</p><div className="mt-7"><label className="text-sm font-semibold">Username</label><div className="relative mt-2"><AtSign className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,""))} className="input pl-10" placeholder="yourname"/></div></div><div className="mt-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold"><Sparkles size={16}/> Suggested usernames</div><button onClick={()=>suggest(name)} className="text-xs font-semibold text-orange-600"><RefreshCw size={13} className="mr-1 inline"/>Refresh</button></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{suggestions.map(s=><button key={s} onClick={()=>setUsername(s)} className={"rounded-xl border px-4 py-3 text-left text-sm font-semibold transition "+(username===s?"border-orange-500 bg-orange-50":"border-slate-200 hover:bg-slate-50")}><span>@{s}</span>{username===s&&<Check size={15} className="float-right text-orange-600"/>}</button>)}</div></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<button disabled={saving} onClick={save} className="btn btn-primary mt-7 w-full py-3.5">{saving?<Loader2 size={17} className="animate-spin"/>:<Check size={17}/>}Continue to CreatorHub</button></div></div></main>
}
