"use client";
import {useEffect,useRef,useState} from "react";
import {motion,useScroll,useSpring,useTransform} from "framer-motion";
import Lenis from "lenis";
import Image from "next/image";

export function SmoothScroll(){useEffect(()=>{const lenis=new Lenis({duration:1.15,smoothWheel:true});let raf=0;const frame=(t:number)=>{lenis.raf(t);raf=requestAnimationFrame(frame)};raf=requestAnimationFrame(frame);return()=>{cancelAnimationFrame(raf);lenis.destroy()}},[]);return null}

export function PublicHeader({signedIn=false}:{signedIn?:boolean}){const [compact,setCompact]=useState(false);useEffect(()=>{const on=()=>setCompact(window.scrollY>40);window.addEventListener("scroll",on,{passive:true});return()=>window.removeEventListener("scroll",on)},[]);return <motion.header initial={{y:-20,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.6,ease:[.16,1,.3,1]}} className="sticky top-0 z-50 border-b border-white/20 bg-[#0A1931]/90 text-white backdrop-blur-xl"><div className={`mx-auto flex max-w-7xl items-center justify-between px-5 transition-all duration-500 ${compact?"h-14":"h-20"}`}><a href="/" className="flex items-center gap-3"><Image src="/creatorhub-mark.svg" width={40} height={40} alt="CreatorHub"/><span className="font-bold tracking-tight">CreatorHub</span></a><div className="flex items-center gap-2"><a href={signedIn?"/dashboard":"/auth/sign-in"} className="rounded-full border border-white/20 px-4 py-2 text-sm font-semibold transition hover:bg-white/10">{signedIn?"Workspace":"Sign in"}</a><a href={signedIn?"/dashboard":"/auth/sign-up"} className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-[#0A1931] transition hover:scale-[1.03]">{signedIn?"Open workspace":"Sign up"}</a></div></div><div className="mx-auto hidden max-w-7xl px-5 pb-3 md:block"><div className="inline-flex rounded-full border border-white/15 bg-white/5 p-1 text-xs font-semibold"><a href="/" className="rounded-full bg-white px-4 py-2 text-[#0A1931]">Personal</a><a href="/advertiser" className="rounded-full px-4 py-2 text-white/70 transition hover:text-white">Business</a></div></div></motion.header>}

export function ScrollHero(){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start start","end start"]});const scale=useTransform(scrollYProgress,[0,1],[.9,1.2]);const imageScale=useTransform(scrollYProgress,[0,1],[1,1.3]);const y=useTransform(scrollYProgress,[0,1],[100,-100]);return <section ref={ref} className="relative h-[190vh] bg-[#0A1931] text-white"><div className="sticky top-0 flex min-h-screen items-center overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_25%,rgba(253,185,19,.24),transparent_32%),radial-gradient(circle_at_10%_70%,rgba(96,205,255,.18),transparent_30%)]"/><div className="relative mx-auto grid w-full max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="z-10"><div className="mb-6 inline-flex rounded-full border border-[#FDB913]/40 bg-[#FDB913]/10 px-4 py-2 text-xs font-semibold text-[#FDB913]">Ghana creator economy · built for real operations</div><div className="overflow-hidden"><motion.h1 style={{y}} className="max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">Advertise.<br/>Create.<br/><span className="text-[#FDB913]">Earn smarter.</span></motion.h1></div><p className="mt-7 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">Campaigns, creators, Google Ads, Paystack payments and accountable earnings in one connected workspace.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/auth/sign-up" className="rounded-full bg-[#FDB913] px-6 py-3 font-bold text-[#0A1931] transition hover:scale-105">Start with CreatorHub</a><a href="/how-it-works" className="rounded-full border border-white/20 px-6 py-3 font-semibold transition hover:bg-white/10">See how it works</a></div></div><motion.div style={{scale}} className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-10 rounded-[3rem] bg-[#FDB913]/15 blur-3xl"/><div className="relative overflow-hidden rounded-[32px] bg-white p-3 shadow-2xl shadow-black/40"><motion.div style={{scale:imageScale}} className="overflow-hidden rounded-[24px]"><Image src="/hero-campaigns.svg" width={1000} height={760} priority className="h-auto w-full" alt="CreatorHub campaign workspace"/></motion.div><div className="flex items-center justify-between px-4 py-4 text-[#0A1931]"><div><div className="text-xs font-semibold uppercase tracking-wider text-slate-400">Live campaign operations</div><div className="mt-1 font-bold">One workspace. Real outcomes.</div></div><div className="h-10 w-10 rounded-full bg-[#FDB913]"/></div></div></motion.div></div></div></section>}

const sections=[["Run real YouTube Ads with Google Ads API","Launch measurable campaigns with connected ad operations instead of unverifiable traffic.","/hero-about.svg"],["Get GH₵ for creator campaigns","Keep creator Coins and GHS cash balances separate while campaign work moves through verification.","/hero-creators.svg"],["Pay via Paystack, Earn via MoMo","Connect funding, verified transactions and creator withdrawals into a traceable Ghana-first workflow.","/hero-support.svg"]];
export function ProductStory(){return <>{sections.map(([title,body,image],i)=><Story key={title} title={title} body={body} image={image} index={i}/>)}</>}
function Story({title,body,image,index}:{title:string;body:string;image:string;index:number}){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const y=useTransform(scrollYProgress,[0,1],[80,-80]);const scale=useSpring(useTransform(scrollYProgress,[0,.5,1],[.92,1,1.06]),{stiffness:90,damping:24});return <section ref={ref} className="relative h-[150vh] bg-white"><div className="sticky top-0 flex min-h-screen items-center overflow-hidden"><div className={`mx-auto grid w-full max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:items-center ${index%2?"lg:[&>div:first-child]:order-2":""}`}><motion.div style={{y}} className="max-w-xl"><div className="mb-5 text-sm font-bold text-[#0A1931]">0{index+1} / CREATORHUB</div><h2 className="text-4xl font-semibold tracking-[-.04em] text-slate-950 sm:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{body}</p><a href="/auth/sign-up" className="mt-7 inline-flex rounded-full bg-[#0A1931] px-5 py-3 font-semibold text-white transition hover:scale-105">Explore the workflow</a></motion.div><motion.div style={{scale}} className="relative"><div className="absolute -inset-8 rounded-[3rem] bg-[#FDB913]/10 blur-3xl"/><div className="relative overflow-hidden rounded-[32px] border border-slate-200 bg-slate-50 p-3 shadow-2xl"><Image src={image} width={900} height={700} className="h-[420px] w-full rounded-[24px] object-cover" alt={title}/><div className="absolute bottom-7 left-7 right-7 rounded-2xl bg-white/90 p-5 shadow-lg backdrop-blur"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Ghana</div><div className="mt-1 text-lg font-bold text-[#0A1931]">{index===0?"Campaign reporting":index===1?"Creator earnings":"Verified payments"}</div></div></div></motion.div></div></div></section>}
