"use client";

import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import { ArrowLeft, Download, ExternalLink, FileText, Loader2, QrCode, Search, Database } from "lucide-react";
import Link from "next/link";
import { supabase } from "@/lib/supabase";

const tables=["profiles","campaigns","creator_applications","campaign_applications","transactions","referrals","notifications","audit_logs","google_ads_connections","api_keys","creator_memberships","support_requests","payment_complaints"] as const;
type Row=Record<string,unknown>;

export default function MonitoringDetails({searchParams}:{searchParams:{table?:string}}){
 const table=tables.includes(searchParams.table as typeof tables[number])?searchParams.table!:"transactions";
 const [rows,setRows]=useState<Row[]>([]); const [selected,setSelected]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [query,setQuery]=useState("");
 useEffect(()=>{(async()=>{setLoading(true);const {data}=await supabase().from(table).select("*").order("created_at",{ascending:false}).limit(500);setRows((data||[]) as Row[]);setLoading(false)})()},[table]);
 const filtered=useMemo(()=>rows.filter(r=>!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const exportRows=(format:"csv"|"json")=>{const payload=filtered;const text=format==="json"?JSON.stringify(payload,null,2):toCsv(payload);const blob=new Blob([text],{type:format==="json"?"application/json":"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`creatorhub-${table}-${Date.now()}.${format}`;a.click();URL.revokeObjectURL(a.href)};
 return <AppShell admin><div className="mx-auto max-w-7xl">
  <Link href="/admin/monitoring" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-900"><ArrowLeft size={15}/> System monitoring</Link>
  <div className="mt-5 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-orange-600">Operational records</p><h1 className="mt-2 text-3xl font-semibold">{table.replaceAll("_"," ")}</h1><p className="mt-2 text-sm text-slate-500">{filtered.length} records available in this view.</p></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={()=>exportRows("csv")}><Download size={15}/> CSV</button><button className="btn btn-secondary" onClick={()=>exportRows("json")}><FileText size={15}/> JSON</button></div></div>
  <div className="card mt-6 overflow-hidden"><div className="border-b border-slate-200 p-4"><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3"><Search size={15} className="text-slate-400"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Search every field in these records" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
   {loading?<div className="p-12 text-center"><Loader2 className="mx-auto animate-spin text-orange-600"/></div>:<div className="divide-y divide-slate-100">{filtered.map((r,i)=>{const id=String(r.id||i);return <button key={id} onClick={()=>setSelected(r)} className="w-full p-5 text-left hover:bg-slate-50"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="font-mono text-xs font-semibold truncate">{String(r.reference||r.id||"Record")}</div><div className="mt-1 text-sm text-slate-600 truncate">{String(r.description||r.subject||r.title||r.email||r.type||"Operational record")}</div></div><div className="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{String(r.status||"RECORDED")}</div></div><div className="mt-2 text-xs text-slate-400">{r.created_at?new Date(String(r.created_at)).toLocaleString():"No timestamp"} · Open complete details</div></button>})}</div>}
   {!loading&&!filtered.length&&<div className="p-12 text-center text-sm text-slate-500">No records found.</div>}</div>

  {selected&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-4 md:p-8" onClick={()=>setSelected(null)}><div className="mx-auto flex h-full max-w-4xl items-center" onClick={e=>e.stopPropagation()}><div className="max-h-[90vh] w-full overflow-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-600">Complete record</p><h2 className="mt-1 font-bold">{String(selected.reference||selected.id||"Record")}</h2></div><button className="btn btn-secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="grid gap-6 p-6 lg:grid-cols-[1fr_260px]"><div className="rounded-2xl bg-slate-950 p-5 text-slate-100"><pre className="whitespace-pre-wrap break-words text-xs leading-6">{JSON.stringify(selected,null,2)}</pre></div><div className="space-y-4"><div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><QrCode size={17}/> Scan exact record</div><img className="mx-auto mt-4 h-48 w-48 rounded-xl border border-slate-200 p-2" src={qrUrl(table,String(selected.id||""))} alt="Record QR code"/><p className="mt-3 text-center text-[11px] text-slate-500">Scanning opens the protected record in CreatorHub.</p></div><button className="btn btn-secondary w-full" onClick={()=>navigator.clipboard?.writeText(window.location.origin+`/admin/monitoring/${String(selected.id||"")}?table=${table}`)}><ExternalLink size={15}/> Copy record link</button></div></div></div></div></div>}
 </div></AppShell>
}
function qrUrl(table:string,id:string){return "https://quickchart.io/qr?size=500&text="+encodeURIComponent(window.location.origin+"/admin/monitoring/"+encodeURIComponent(id)+"?table="+encodeURIComponent(table))}
function toCsv(rows:Row[]){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];const esc=(v:unknown)=>`"${String(typeof v==="object"&&v!==null?JSON.stringify(v):v??"").replaceAll('"','""')}"`;return [keys.join(","),...rows.map(r=>keys.map(k=>esc(r[k])).join(","))].join("\n")}
