'use client';
import {useEffect,useState} from "react";import Link from "next/link";import {ArrowUpRight,Clock3,Coins,Plus,WalletCards,Users,TrendingUp,BriefcaseBusiness,FileText,UserRound,ChevronRight,Activity,ShieldCheck} from "lucide-react";import AppShell from "@/components/AppShell";import {supabase} from "@/lib/supabase";
type Profile={display_name:string|null;coins:number;cash_balance:number;pending_cash:number;role:string};type Campaign={id:string;title:string;kind:string;status:string;budget:number;spent:number;created_at:string};
export default function Dashboard(){const [profile,setProfile]=useState<Profile|null>(null);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const s=supabase();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/auth/sign-in";return}const [pr,ca]=await Promise.all([s.from("profiles").select("display_name,coins,cash_balance,pending_cash,role").eq("id",user.id).single(),s.from("campaigns").select("id,title,kind,status,budget,spent,created_at").eq("status","ACTIVE").order("created_at",{ascending:false}).limit(5)]);setProfile(pr.data);setCampaigns(ca.data||[]);setLoading(false)})()},[]);
return <AppShell admin={profile?.role==="ADMIN"}><div className="mx-auto max-w-7xl"><div className="relative overflow-hidden rounded-[28px] bg-[#0A1931] p-7 text-white shadow-xl lg:p-10"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-[#FDB913]/15 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#FDB913]">CreatorHub command center</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Good to see you{profile?.display_name?", "+profile.display_name:""}.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Your campaigns, creator work, financial activity and account controls are connected here.</p></div><Link href="/campaigns" className="inline-flex items-center gap-2 rounded-full bg-[#FDB913] px-5 py-3 text-sm font-bold text-[#0A1931]"><BriefcaseBusiness size={17}/>Explore campaigns</Link></div></div>
{loading?<Skeleton/>:<><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Coins} label="Coins balance" value={(profile?.coins||0).toLocaleString()} href="/earnings"/><Stat icon={WalletCards} label="Available GHS" value={"GH₵"+(profile?.cash_balance||0).toFixed(2)} href="/earnings"/><Stat icon={Clock3} label="Pending GHS" value={"GH₵"+(profile?.pending_cash||0).toFixed(2)} href="/earnings"/><Stat icon={Users} label="Account role" value={profile?.role||"USER"} href="/profile"/></div>
<div className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 className="font-semibold">Available campaigns</h2><p className="mt-1 text-xs text-slate-500">Current active opportunities you can open and review.</p></div><Link href="/campaigns" className="text-sm font-semibold text-orange-600">View all</Link></div><div className="divide-y divide-slate-100">{campaigns.length?campaigns.map(c=><Link href={"/campaigns/"+c.id} key={c.id} className="flex items-center justify-between p-5 transition hover:bg-slate-50"><div><div className="font-semibold text-sm">{c.title}</div><div className="mt-1 text-xs text-slate-500">{c.kind.replace("_"," ")} · Budget GH₵{Number(c.budget).toLocaleString()}</div></div><ArrowUpRight size={18} className="text-slate-400"/></Link>):<div className="p-10 text-center text-sm text-slate-500">No active campaigns are available right now.</div>}</div></section>
<section className="space-y-4"><Quick href="/campaigns" icon={BriefcaseBusiness} title="Campaign workspace" text="Browse active campaigns, applications and campaign details."/><Quick href="/creator" icon={UserRound} title="Creator Program" text="Review membership and apply for creator participation."/><Quick href="/earnings" icon={WalletCards} title="Financial history" text="Open verified earnings, balances and transaction records."/><Quick href="/activity" icon={Activity} title="Account activity" text="Review recent actions and platform events."/><Quick href="/settings" icon={ShieldCheck} title="Account controls" text="Manage profile, security, privacy and developer access."/></section></div>
<div className="mt-6 grid gap-4 md:grid-cols-3"><Mini href="/referrals" icon={Users} title="Referrals" text="Open your referral activity and eligible commissions."/><Mini href="/developers" icon={FileText} title="Developer center" text="Review API access, integration guidance and terms."/><Mini href="/help-center" icon={ShieldCheck} title="Help center" text="Search platform guidance and troubleshooting." /></div></>}</div></AppShell>}
function Stat({icon:Icon,label,value,href}:{icon:any;label:string;value:string;href:string}){return <Link href={href} className="card block p-5 transition hover:-translate-y-0.5 hover:shadow-md"><Icon size={19} className="text-orange-600"/><div className="mt-4 text-xl font-bold">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></Link>}
function Quick({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href:string}){return <Link href={href} className="card flex items-center gap-4 p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="rounded-xl bg-slate-100 p-3"><Icon size={18}/></div><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{text}</div></div><ChevronRight size={17} className="text-slate-400"/></Link>}
function Mini({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href:string}){return <Link href={href} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-slate-300 hover:shadow-sm"><Icon size={18} className="text-orange-600"/><div className="mt-4 font-semibold text-sm">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{text}</div></Link>}
function Skeleton(){return <div className="mt-6 space-y-5 animate-pulse"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-32 rounded-xl bg-slate-200"/>)}</div><div className="h-80 rounded-xl bg-slate-200"/></div>}
